name: Checkout, setup Node, and install dependencies
description: Checks out the repo, sets up Node.js via .nvmrc, enables corepack, and installs dependencies.

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v6
    - name: Setup Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc
    - name: Enable corepack
      shell: bash
      run: corepack enable
    - name: Install dependencies
      shell: bash
      run: yarn install --immutable
